### ISSUE TITLE
No release for over a year

### ISSUE THREAD

**Issue by boyedarat** [yuk7/wsldl#141]
Can we have a new release of the executables?
The last release was almost 17 months ago.

**Comment by yuk7** [comment]
I plan to release a new version in the near future.
I apologize for not releasing a new version for a long time.
Sorry,

**Comment by amzwrk** [comment]
Hi @yuk7, you've created an amazing piece of software which works perfectly even on the latest versions of WSL and with most distros. Don't feel pressured. I'm sure everyone just wanted to know that the project and dev is still active even if its not constantly being updated. (One of my favourite pieces of software BSPWM has been deemed feature complete and hasn't had a new release since 2020). So cheers and thanks again for this awesome piece of software!

**Comment by boyedarat** [comment]
@yuk7 Thanks for updating the release.
