### ISSUE TITLE
 Register to WSL?

### ISSUE THREAD

**Issue by cataquil** [yuk7/wsldl#29]
I can run the .exe in cmd and get the distro, but how can I register this so I have it as a tile like the Ubuntu I installed from ms store.  is is with lxrun?  did this get depreciated?  thanks

**Comment by yuk7** [comment]
It is a launcher similar to ms store's Ubuntu.
At the time of creating this, Microsoft created because it did not distribute the launcher source code.
The difference is as follows:
* Not a Store Application
* You can use any rootfs.
* Customizable distribution name
* The command line is more versatile.

**Comment by yuk7** [comment]
I'm sorry, my English is not good...
Registration to WSL is done by exe.

**Comment by binarylandscapes** [comment]
@cataquil so lxrun is pre Windows v1703 I think? You can install following the instructions and if you run "wslconfig /l" It will show all your distros and which one is default. "wsl" invokes the default and using wslconfig you can change the default
